### ISSUE TITLE
Autor-Verlinkung in Blogpost mit Leerzeichen statt "-"

### ISSUE THREAD

**Issue by antondachauer** [getherbie/herbie#10]
Hallo, habe noch ein Problem festgestellt. Wenn ich als Autor einen Namen mit Leerzeichen wie zb. "Hans Peter" eingebe, wird die URL zur Autorenseite mit Leerzeichen statt "-" generiert (also "blog/author/hans peter", müsste aber "blog/author/hans-peter", damit die angelegte Seite gefunden und angezeigt wird.

**Comment by tbreuss** [comment]
Danke für den Hinweis. Dies schaue ich mir ebenfalls morgen an.

**Comment by tbreuss** [comment]
Das Problem ist mit 4762081510866a23a8da6bfe11feb11155b7b355 gelöst.
