### ISSUE TITLE
"blocks" löschen/überschreiben die Inhalts-Segmente der Eltern-Seite 

### ISSUE THREAD

**Issue by Netzweberei** [getherbie/herbie#17]
Hi Thomas,
sobald man Unterseiten mit Hilfe des blocke-shortcodes anzeigen lässt, gehen in der Folge alle bereits geladenen Segmente der Eltern-Seite verloren. Es bleiben nur noch die Segmente des letzten gefundenen Blocks erhalten.

Nach dem Aufruf in herbei/plugins/twig/classes/Twig.php#148:
 
$segment->string = Hook::trigger(Hook::FILTER, 'renderContent', $segment->string, $page->getData());

ist alles weg :-(
Ich sitze jetzt schon eine ganze Weile drüber, kann aber die Ursache nicht finden.

Viele Grüße,
Andreas

**Comment by tbreuss** [comment]
Hi Andreas

Danke für die Rückmeldung. Ich schau mir das morgen. Ist grad viel los zur Zeit.

LG
Thomad

Von meinem iPod gesendet

**Comment by tbreuss** [comment]
Fixed with https://github.com/getherbie/herbie/commit/3dec7c345d1ef2029cc49c8adbf369203e344695

Kannst Du mal schauen, ob das funktioniert?

**Comment by Netzweberei** [comment]
Am 16.10.2015 um 21:06 schrieb Thomas Breuss <notifications@github.com>:

> Kannst Du mal schauen, ob das funktioniert?

Funktioniert!

Danke
