### ISSUE TITLE
adminpanel not working

### ISSUE THREAD

**Issue by smpcasgit** [getherbie/herbie#24]
did : composer require getherbie/plugin-adminpanel

did: plugins:
enable:
- adminpanel

did: plugins:
config:
adminpanel:
show_raw_data: true
password: "md5encoded"
layouts:
default.html:
...

debian 8, nginx 1.8.0

**Comment by tbreuss** [comment]
Thanks for reporting. I'll take a look on it tomorrow.

**Comment by tbreuss** [comment]
In the meantime I'm working on version 2 of Herbie, which is shipped with an included version of the adminpanel plugin. The old adminpanel version is not supported any more.

So, I'm closing this issue.
