### ISSUE TITLE
Wie kann ich Herbie CMS upgraden

### ISSUE THREAD

**Issue by AlexL777** [getherbie/herbie#31]
Hallo Entwickler,

ich würde gerne Herbie upgraden, sehe aber in den Codes, dass sich etwas verändert hat. Ich habe noch die Version 1.0 und nun steht mir ein Upgrade bevor.

Mit Composer Update klappt es nicht, weil wohl mein Herbie System irgendwelche Voraussetzungen nicht erfüllen kann. 

Wie kann ich es nun anstellen?

Danke im Vorfeld, Alexander

**Comment by tbreuss** [comment]
Hallo Alexander
Was steht denn in deiner composer.json Projekt-Datei? Ist dort fix eine Version 1.0.0 "verdrahtet"?
Und bist du sicher, dass Version 1.0.0 installiert ist und nicht 1.0.1? Du kannst dies mit `composer info` herausfinden. Version 1.0.1 bringt übrigens auch keine neuen Features, ein Update ist nicht zwingend notwendig.
LG, Thomas

**Comment by AlexL777** [comment]
Hallo Thomas,

vielen Dank für deine rasche Rückmeldung. Ich bin jetzt klar gekommen. Du hattest mir damals erlaubt, Herbie als Webseite zu nutzen, so wie du es auf der offiziellen Webseite hast. Ich hatte nur etliche Inhalte gelöscht, damit es kein DC erzeugt und habe etwas gebloggt. 

Jetzt habe ich noch die aktuelle .json-Datei hochgeladen und dann das Composer Update gemacht. Dann klappte auch schon alles.
