### ISSUE TITLE
Wie kann ich ein Download in Herbie CMS anbieten

### ISSUE THREAD

**Issue by AlexL777** [getherbie/herbie#32]
Hi Thomas,

eine ganze Weile ist es her als wir den letzten Kontakt miteinander hatten. Da habe ich inzwischen viele CMS installiert und kam wieder auf das Herbie CMS, was ich unter http://herbie.wpzweinull.ch habe.

Ich wollte wissen, wie man einen Download anbieten kann? Ich habe dazu eine Seite und auf der würde ich gerne eine ZIP-Datei zum Herunterladen anbieten. Das ZIP kann dann gerne im FTP-Account aufbewahrt werden. Ist das irgendwie möglich, vielleicht mit einem hübschen Downloadbutton oder so etwas?

Danke im Vorfeld.

**Comment by tbreuss** [comment]
Hi Alex, Downloads kann man in Herbie wie folgt erzeugen:

{{ file_link('pdf/dummy.pdf', 'Dummy Download', true) }}

Die referenzierte Datei muss im Verzeichnis `site/media/pdf/` abgelegt sein.

Siehe auch: https://raw.githubusercontent.com/getherbie/start-website/master/site/pages/3-about.md
