### ISSUE TITLE
Probleme mit https bei Herbie CMS

### ISSUE THREAD

**Issue by AlexL777** [getherbie/herbie#33]
Hi nochmals,

wollte heute Herbie mit SSL betreiben, aber sah schon, dass unter /adminpanel die Login-Maske nicht richtig dargestellt wurde. Muss ich im System oder den Files für SSL etwas einstellen oder reicht es, dass ich es beim Webhoster habe?

In .htaccess den Redirect hatte ich aber ermöglicht.

**Comment by tbreuss** [comment]
Dies sollte behoben sein mit Version https://github.com/getherbie/herbie/releases/tag/v2.0.0-RC1.
Dies ist allerdings ein kompletter Rewrite und bringt einige nicht rückwärtskompatible Änderungen mit.
