### ISSUE TITLE
3 Fragen zum Herbie Flat File CMS

### ISSUE THREAD

**Issue by AlexL777** [getherbie/herbie#35]
Hallo Entwickler,

eine ganze Weile war ich im eigenen Herbie Blog nicht mehr und erst heute alles wieder uptodate gebracht. Ich sehe, dass hier auf Github in den Rahmen eher weniger los ist oder wie schaut es bei euch mit der aktuellen Weiterentwicklung des Herbie CMS aus?

Gerne würde ich neue Plugins ausprobieren und mir eine Technik in Herbie aneignen. Das Admin Panel ist noch nicht optimal, sodass ich mit dem externen Markdown Pad Editor bloggen muss.

## Frage II:

Die Favicon-Integration funktioniert irgendwie bei mir nicht.

Ich habe alle Favicons mit verschiedenen Formaten nach Verzeichnis `/web` hochgeladen, weil es bei mir zugleich Root ist. Und den HMTL-Code für die Scripte habe ich in der `main.html` untergebracht, wo ich etwas mit `<head>....</head>` gesehen habe. So setze ich es in der Regel um.

## Frage III:

Wie kann ich das Github Symbol rechts neben meinen Blogposts entfernen, denn es leitet falsch weiter und meine Webseite ist nicht in Github zu bearbeiten. 

Dann hoffe ich auf eure Antworten und Danke für dieses geniale Flat File CMS 👍

**Comment by tbreuss** [comment]
Hallo Alexander

1) Die Entwicklung ist doch etwas stehen geblieben. Andere Projekte waren wichtiger. Es ist aber geplant, vor allem hinsichtlich Softwarequalität einiges zu verbessern.

2) Das Favicon-Problem hat eigentlich nichts mit Herbie zu tun. Vorausgesetzt du hast das im HEAD des HTMLs korrekt eingebunden. Manchmal hilft ein Löschen des Browser-Caches. Wenn das nichts hilft, schreib nochmals.

3) Kannst du mir sagen, woher der Code stammt, auf den du dich beziehst? Hast du einen Link zu deinem Github-Repo?

Liebe Grüsse,
Thomas

**Comment by AlexL777** [comment]
Hallo Thomas,
ok, Danke dir erstmals für deine schnelle Antwort. Ja, gut, dann wird es mich umso mehr freuen, wenn ihr etwas geplant habt. Herbie werde ich weiter via Github verfolgen.

Das mit dem Favicon werde ich versuchen selbst zu lösen.

Also soweit ich mich entsinnen kann, habe ich die Herbie Webseite von dir, glaube ich noch zu wissen. Ich hatte damals von dir oder einem anderen Entwickler die fertige Version der Webseite bekommen und finde leider im Default Template nicht, woher der Github Icon stammt. 

Das bedeutet, dass die Blogposts direkt in Github bearbeitet werden können. Auf mein Projekt trifft es eher nicht zu und daher würde ich gerne dieses Github Icon entfernen. Hier mal ein Beispiel-Blogpost von gestern bei mir: xxxx

`Edit`: Komischerweise wird der Github Icon nicht mehr angezeigt. Somit ist das Problem erledigt. Danke dir.

**Comment by tbreuss** [comment]
Ja, ich hatte dir glaub ich die Version bereitgestellt. Somit scheint alles i.O.? Ich schliesse dieses Ticket.
