### ISSUE TITLE
URL-Rewriting / Slugs

### ISSUE THREAD

**Issue by antondachauer** [getherbie/herbie#43]
Bei Links, in denen Umlaute vorkommen, wird der Buchstabe weggelassen, statt beispielsweise aus "Ü" "ue" zu machen.

**Comment by tbreuss** [comment]
Betrifft das MenuItems in generierten Menus? Ein Beispiel wäre super.

**Comment by antondachauer** [comment]
Gerne doch! Wenn im Name des Autors ein Umlaut vorkommt, beispielsweise bei "Hans Müller" wird "hans-mller" daraus.

**Comment by tbreuss** [comment]
Ich bin daran, ein Upgrade für PHP 7.2 vorzubereiten. Danach werde ich die Slugify-Methode anpassen. Wird aber noch ein paar Tage dauern.

**Comment by tbreuss** [comment]
Das ging etwas länger als gedacht. In Version 2 ist dieses Problem gefixt.

Wir nutzen als "slugify" Methode das Composer-Package "ausi/slug-generator".

Version 2 wird in ein paar Tagen released.
