### ISSUE TITLE
ParsedownExtra.php

### ISSUE THREAD

**Issue by kissmedve** [getherbie/herbie#58]
Hallo,

wir betreiben seit einigen Jahren mit Herbie eine Website auf Uberspace.de.

Nachdem "kürzlich aus Sicherheitsgründen eine veraltete PHP-Version aus allen uberspaces entfernt" wurde, liefert die Seite nur noch einen 500 Internal Server Error. Laut Uberspace "kann es gut sein, dass [das CMS] jetzt auf veraltete Funktionen zugreifen will und das eben den Fehler verursacht".

Das Apache Errorlog sagt:
PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/virtual/xxx/xxx/vendor/getherbie/herbie/src/plugins/markdown/vendor/ParsedownExtra.php on line 241

Das PHP Errorlog sagt:
"[20-Jun-2022 21:48:40] WARNING: [pool www] child 6936 said into stderr: "NOTICE: PHP message: PHP Notice:  Trying to access array offset on value of type null in /var/www/virtual/xxx/xxxx/vendor/getherbie/herbie/src/plugins/markdown/vendor/ParsedownExtra.php on line 241"

Die /vendor/getherbie/herbie/composer.json sagt:
"require": {
        "php": ">=5.6.0",
        "symfony/yaml": "2.7.*"
    },

Derzeit sind PHP 7.4, 8.0 und 8.1 auf dem Server verfügbar, PHP 7.4 ist standardmäßig installiert - sollte also passen.

Was kann ich tun, um die Installation wieder zum Laufen zu bringen?

Danke im voraus!
Ursula

PS: Übrigens ganz großes Lob für dieses geniale, kleine CMS!

**Comment by tbreuss** [comment]
Das ist mit dieser Fehlermeldung schwierig zu beurteilen. Auf jeden Fall scheint das eine frühe Version von Herbie zu sein. Das sieht man an der verlangten PHP-Version.

Die einfachste Lösung im Sinne eines Supports wäre...
1) wenn du mir die Website als ZIP-Archiv zur Verfügung stellst
2) oder mir temporären Zugang zum Hosting gibst

Ich habe allerdings Ferien und bin entsprechend nur wenig am Compi.

**Comment by tbreuss** [comment]
Ich schliesse dieses Issue, da die Weiterentwicklung von Version 2 wieder Fahrt aufgenommen hat. Das Problem kann somit eigentlich nur mit einem Update auf eine neue Version gelöst werden. Version 2 ist noch Releasekandidat, mit einem Release kann in zwei drei Monaten gerechnet werden.
