### ISSUE TITLE
Pfad zu CSS-File wird nicht korrekt ausgeliefert

### ISSUE THREAD

**Issue by antondachauer** [getherbie/herbie#8]
Hallo,

ich habe gerade wie in der Anleitung herbie installiert. Alles läuft, bis auf eine kleine, wichtige Kleinigkeit: Für das CSS-File in "site/assets/default/css/styles.css" wird folgender HTML-Code zum Einbinden generiert: "<link href="//assets/default/css/styles.css" type="text/css" rel="stylesheet">"

Das sorgt dafür, dass der Browser (zumindest bei mir) die Datei nicht findet.

Danke
Anton

**Comment by antondachauer** [comment]
Wenn ich in vendor/getherbie/herbie/src/Application.php::74 "dirname($_SERVER['SCRIPT_NAME'])" mit "" ersetze, läufts.

**Comment by tbreuss** [comment]
Hallo Anton, danke für die Meldung. Die Lösung von Netzweberei sollte funktionieren. Ich komme allerdings erst morgen dazu, mir das Problem genau anzuschauen. LG

**Comment by antondachauer** [comment]
Hallo Thomas, danke für die Info! Das passt, mein vorläufiger Fix geht ja erstmal! :+1: 

Danke

**Comment by tbreuss** [comment]
Sollte behoben sein mit ba020df96c62b249a54227cf45d2f4157fe0bd98
